<?php

return [
    [
        'id' => 'contact',
        'name' => 'Contact Form',
        'description' => 'Name, email and a message field.',
        'schema' => [
            'title' => 'Contact Form',
            'steps' => [
                [
                    'id' => 'step-contact',
                    'title' => 'Step 1',
                    'sections' => [
                        [
                            'id' => 'section-contact',
                            'title' => 'Your details',
                            'fields' => [
                                [
                                    'id' => 'contact-name',
                                    'type' => 'text',
                                    'key' => 'name',
                                    'label' => 'Full name',
                                    'placeholder' => 'Jane Doe',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'contact-email',
                                    'type' => 'email',
                                    'key' => 'email',
                                    'label' => 'Email address',
                                    'placeholder' => 'jane@example.com',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'contact-message',
                                    'type' => 'textarea',
                                    'key' => 'message',
                                    'label' => 'Message',
                                    'placeholder' => 'How can we help?',
                                    'help' => '',
                                    'default' => null,
                                    'required' => false,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'id' => 'event',
        'name' => 'Event Registration',
        'description' => 'Attendee details and ticket selection.',
        'schema' => [
            'title' => 'Event Registration',
            'steps' => [
                [
                    'id' => 'step-event',
                    'title' => 'Registration',
                    'sections' => [
                        [
                            'id' => 'section-event',
                            'title' => 'Attendee',
                            'fields' => [
                                [
                                    'id' => 'event-name',
                                    'type' => 'text',
                                    'key' => 'full_name',
                                    'label' => 'Full name',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'event-email',
                                    'type' => 'email',
                                    'key' => 'email',
                                    'label' => 'Email',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'event-ticket',
                                    'type' => 'dropdown',
                                    'key' => 'ticket_type',
                                    'label' => 'Ticket type',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [
                                        ['label' => 'General', 'value' => 'general'],
                                        ['label' => 'VIP', 'value' => 'vip'],
                                        ['label' => 'Student', 'value' => 'student'],
                                    ],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'event-count',
                                    'type' => 'number',
                                    'key' => 'attendee_count',
                                    'label' => 'Number of attendees',
                                    'placeholder' => '1',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => 1,
                                    'max' => 10,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'id' => 'feedback',
        'name' => 'Customer Feedback',
        'description' => 'Satisfaction rating, recommendation and comments.',
        'schema' => [
            'title' => 'Customer Feedback',
            'steps' => [
                [
                    'id' => 'step-feedback',
                    'title' => 'Feedback',
                    'sections' => [
                        [
                            'id' => 'section-feedback',
                            'title' => 'Tell us how we did',
                            'fields' => [
                                [
                                    'id' => 'feedback-rating',
                                    'type' => 'rating',
                                    'key' => 'satisfaction',
                                    'label' => 'How satisfied were you?',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => 1,
                                    'max' => 5,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'feedback-recommend',
                                    'type' => 'radio',
                                    'key' => 'recommend',
                                    'label' => 'Would you recommend us?',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [
                                        ['label' => 'Yes', 'value' => 'yes'],
                                        ['label' => 'No', 'value' => 'no'],
                                    ],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'feedback-comments',
                                    'type' => 'textarea',
                                    'key' => 'comments',
                                    'label' => 'Comments',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => false,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'feedback-contact',
                                    'type' => 'checkbox',
                                    'key' => 'contact_allowed',
                                    'label' => 'Can we contact you for a follow-up?',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => false,
                                    'options' => [
                                        ['label' => 'Yes, please', 'value' => 'yes'],
                                    ],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
    [
        'id' => 'application',
        'name' => 'Job Application',
        'description' => 'Candidate details, position and availability.',
        'schema' => [
            'title' => 'Job Application',
            'steps' => [
                [
                    'id' => 'step-app',
                    'title' => 'Application',
                    'sections' => [
                        [
                            'id' => 'section-app',
                            'title' => 'About you',
                            'fields' => [
                                [
                                    'id' => 'app-name',
                                    'type' => 'text',
                                    'key' => 'full_name',
                                    'label' => 'Full name',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'app-email',
                                    'type' => 'email',
                                    'key' => 'email',
                                    'label' => 'Email',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'app-position',
                                    'type' => 'dropdown',
                                    'key' => 'position',
                                    'label' => 'Position applied for',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [
                                        ['label' => 'Engineering', 'value' => 'engineering'],
                                        ['label' => 'Design', 'value' => 'design'],
                                        ['label' => 'Marketing', 'value' => 'marketing'],
                                    ],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                                [
                                    'id' => 'app-availability',
                                    'type' => 'radio',
                                    'key' => 'availability',
                                    'label' => 'Availability',
                                    'placeholder' => '',
                                    'help' => '',
                                    'default' => null,
                                    'required' => true,
                                    'options' => [
                                        ['label' => 'Immediately', 'value' => 'immediately'],
                                        ['label' => 'Two weeks notice', 'value' => 'two_weeks'],
                                        ['label' => 'One month', 'value' => 'one_month'],
                                    ],
                                    'min' => null,
                                    'max' => null,
                                    'regex' => '',
                                    'validation' => [],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
